version: 2
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            npm install
      - run:
          name: build site
          command: |
            npm run build
